name: Run Lighthouse with Minimum Score Enforcement

on:
  push:
    branches: [fix/optionnalThresholds]
  pull_request:
    branches: [master]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Lighthouse check
        uses: Spartakyste/lighthouse-ci@main
        with:
          urls: "http://example.com/"
          token: ${{ secrets.GITHUB_TOKEN }}
          #performanceThreshold: 100
          accessibilityThreshold: 90
          bestPracticesThreshold: 25
          SEOThreshold: 67
          PWAThreshold: 20
